/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.conectar;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author PAULA BLANCO
 */
public class formulario extends javax.swing.JFrame {
    
    conectar conecto;
    
    PreparedStatement ps;
    ResultSet rs;
    
     private static Connection conn; 
    private static final String driver = "com.mysql.jdbc.Driver";
    private static final String user = "root";
    private static final String pass = "";
    private static final String url = "jdbc:mysql://localhost:3306/dbjuzgado";
    
    public formulario (){
        initComponents();
    }
    
    //este metodo nos retorna la conexion 
    public Connection getConnection (){
        
        Connection conn = null; 
        try {
            Class.forName(driver);
            conn = DriverManager.getConnection (url, user, pass);
        if (conn != null){
            System.out.println ("La conexión se estalecio bien con la DB");
            }
        } catch (ClassNotFoundException | SQLException e){
            System.out.println ("Error al conectar con la BD" + e);
        }
        return conn;
        
    }
    
    //metodo para desconectar 
    public void desconectar (){
        conn = null;
        if (conn == null){
            System.out.println ("Se desconecto de la DB");
        }
    }
    
    
    public void borrarCajas (){
     CajaDistrito.setText(null);
     CajaInstancia.setText(null);
     CajaEspecialidad.setText(null);
     CajaSubespecialidad.setText(null);
     CajaBaselegal.setText(null);
     
    
    }

    /**
     * Creates new form formulario
     *

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CajaDistrito = new javax.swing.JTextField();
        CajaInstancia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Bconectar = new javax.swing.JButton();
        Bdesconectar = new javax.swing.JButton();
        Benviar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CajaSubespecialidad = new javax.swing.JTextField();
        CajaBaselegal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CajaEspecialidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JLfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Distrito");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Instancia");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setText("Especialidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        CajaDistrito.setBackground(new java.awt.Color(255, 255, 204));
        CajaDistrito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CajaDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaDistritoActionPerformed(evt);
            }
        });
        getContentPane().add(CajaDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 240, -1));

        CajaInstancia.setBackground(new java.awt.Color(255, 255, 204));
        CajaInstancia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CajaInstancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaInstanciaActionPerformed(evt);
            }
        });
        getContentPane().add(CajaInstancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 240, -1));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 3, 48)); // NOI18N
        jLabel4.setText("FORMULARIO ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, 50));

        Bconectar.setBackground(new java.awt.Color(153, 153, 153));
        Bconectar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Bconectar.setText("CONECTAR ");
        Bconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BconectarActionPerformed(evt);
            }
        });
        getContentPane().add(Bconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, -1));

        Bdesconectar.setBackground(new java.awt.Color(153, 153, 153));
        Bdesconectar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Bdesconectar.setText("DESCONECTAR");
        Bdesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdesconectarActionPerformed(evt);
            }
        });
        getContentPane().add(Bdesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, -1));

        Benviar.setBackground(new java.awt.Color(153, 153, 153));
        Benviar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Benviar.setText("ENVIAR");
        Benviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BenviarActionPerformed(evt);
            }
        });
        getContentPane().add(Benviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setText("Subespecialidad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setText("Base legal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        CajaSubespecialidad.setBackground(new java.awt.Color(255, 255, 204));
        CajaSubespecialidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(CajaSubespecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 240, -1));

        CajaBaselegal.setBackground(new java.awt.Color(255, 255, 204));
        CajaBaselegal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(CajaBaselegal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 240, -1));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel7.setText("DE REGISTRO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        CajaEspecialidad.setBackground(new java.awt.Color(255, 255, 204));
        CajaEspecialidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CajaEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaEspecialidadActionPerformed(evt);
            }
        });
        getContentPane().add(CajaEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 240, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura.JPG"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        JLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/justicia-no-se-consulta-articulo-milenio-900x600.jpg"))); // NOI18N
        JLfondo.setMaximumSize(new java.awt.Dimension(725, 454));
        JLfondo.setMinimumSize(new java.awt.Dimension(725, 454));
        getContentPane().add(JLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -20, 820, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CajaInstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaInstanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaInstanciaActionPerformed

    private void CajaDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaDistritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaDistritoActionPerformed

    //Comportamiento del boton 
    
    private void BconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BconectarActionPerformed
        conecto = new conectar ();
        Connection reg = conecto.getConnection ();
    }//GEN-LAST:event_BconectarActionPerformed

    private void BdesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdesconectarActionPerformed
        conecto.desconectar ();
    }//GEN-LAST:event_BdesconectarActionPerformed

    private void BenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BenviarActionPerformed
      Connection conn = null;
      
        try {
            conn = getConnection();
            ps = conn.prepareStatement("INSERT INTO registro (fechareg, distrito, instancia,especialidad,subespecialidad,baselegal)VALUES (?,?,?,?,?,?)");
            ps.setDate(1, Date.valueOf(LocalDate.now()));
            ps.setString(2, CajaDistrito.getText());
            ps.setString(3, CajaInstancia.getText());
            ps.setString(4, CajaEspecialidad.getText());
            ps.setString(5, CajaSubespecialidad.getText());
            ps.setString(6, CajaBaselegal.getText());
            
            
            int result = ps.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Los datos fueron enviados correctamente");
                borrarCajas ();
                
            }else{
                JOptionPane.showMessageDialog(null, "Los datos no fueron enviados");
              }
            conn.close ();
            
        } catch (Exception e) {
            System.out.println (e);
        }
    }//GEN-LAST:event_BenviarActionPerformed

    private void CajaEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaEspecialidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bconectar;
    private javax.swing.JButton Bdesconectar;
    private javax.swing.JButton Benviar;
    private javax.swing.JTextField CajaBaselegal;
    private javax.swing.JTextField CajaDistrito;
    private javax.swing.JTextField CajaEspecialidad;
    private javax.swing.JTextField CajaInstancia;
    private javax.swing.JTextField CajaSubespecialidad;
    private javax.swing.JLabel JLfondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
